### ISSUE TITLE
[BUG: External]

### ISSUE THREAD

**Issue by shen-me-gui** [tnichols217/obsidian-columns#27]
# Describe the bug
When writing the following text using the Obsidian Obsidian's Obsidian columns plug-in, the following errors will be reported

## Steps To Reproduce
`````
````col-md
>[!tips]+ 123
>```vba
>=IFERROR(VLOOKUP(A2,春,2,FALSE),VLOOKUP(A2,夏,2,FALSE))
>```
````
`````
Reading view and live preview will bleed the same error
display
>Dataview (for inline query '=IFERROR(VLOOKUP(A2,春,2,FALSE),VLOOKUP(A2,夏,2,FALSE))'): Unrecognized function name 'VLOOKUP'

## Expected behavior
The contents of the tag should not be displayed

## Screenshots
<img width="731" alt="微信截图_20220619004801" src="https://user-images.githubusercontent.com/28617749/174448572-8dc6f4fa-24ca-4fd1-a325-4b95c03caa40.png">

## System Info
OS: win10,19044.1706
Obsidian Version: v0.14..15
Plugin Version:  1.1.8

### Other plugin information
Plugin Name:  Dateview
Github Link to Plugin:  https://github.com/blacksmithgu/obsidian-dataview
Plugin Version: 0.5.36

**Comment by tnichols217** [comment]
Somehow I did not get a notification when this issue was made, my appologies. 

However, I do not understand what the issue is? 
When i do not use my plugin, and just dataview i get:
![image](https://user-images.githubusercontent.com/62992267/175343385-c0e94ec1-135d-4395-8623-e294a4455a7d.png)

which is the same behavior as when it is used in conjunction with my plugin. Does this issue only occur when using my plugin, or does it occur with the dataview plugin regardless of using mine or not? If it is instead an issue with the dataview plugin, please file and issue on their repo you linked instead.

I might not be understanding your issue, but if it is a problem with my plugin, please let me know what you think is wrong.

**Comment by tnichols217** [comment]
OH i think i understand now. You are trying to display a vbs function inside obsidian, but dataview shows the error below? This is an issue with dataview, however it is because you started the line with an equals sign, you can check your dataview plugins for your default prefixes:
![image](https://user-images.githubusercontent.com/62992267/175344481-9034bac5-a71f-49fe-a960-55b638c40510.png)
As the default is the equals sign, whenever you start any line inside any codeblock with an equals, it tried to parse it as an inline query. If you would not like dataview to parse the line, either change your default prefix inside settings>dataview or start the line with another character.

If this was a misunderstanding and this was not the issue you mentioned, feel free to reopen this issue!

**Comment by shen-me-gui** [comment]
> OH i think i understand now. You are trying to display a vbs function inside obsidian, but dataview shows the error below? This is an issue with dataview, however it is because you started the line with an equals sign, you can check your dataview plugins for your default prefixes: ![image](https://user-images.githubusercontent.com/62992267/175344481-9034bac5-a71f-49fe-a960-55b638c40510.png) As the default is the equals sign, whenever you start any line inside any codeblock with an equals, it tried to parse it as an inline query. If you would not like dataview to parse the line, either change your default prefix inside settings>dataview or start the line with another character.
> 
> If this was a misunderstanding and this was not the issue you mentioned, feel free to reopen this issue!

yeah，You're right
This is a problem with datevie settings
Thanks for your help
Does this feedback need to be closed or deleted? 
This is my first time to use this feedback function，I don't know if this has affected your project

**Comment by tnichols217** [comment]
Dont worry, i have already marked this issue as closed for you! And no, it does not effect my project. Glad I could have helped you anyway!
