### ISSUE TITLE
[FR] mobile aware layouts 

### ISSUE THREAD

**Issue by rapatel0** [tnichols217/obsidian-columns#42]
# Feature Request
Brief description of feature wanted
I create some dashboards with nice layouts on my desktop but on mobile the end up looking crappy due to clutter. Would be nice if the layout could detect is the screen space is too small and disable/reduce the columns.

**Comment by tnichols217** [comment]
This is already a feature of obsidian columns :]

Go to Settings > Obsidian Columns and modify the min width value to your satisfaction (a higher value means less columns next to each other on mobile) it does effect all screens too but smaller screens will wrap more often because of smaller screen space.

**Comment by tnichols217** [comment]
If you have tried that and would like additional customization, please describe what you would like different

**Comment by tnichols217** [comment]
I don't believe this is an issue, as it is already implemented. Closing
